---
title: "First Day Checklist"
subtitle: "Essential Information for Your First Day at NOAA-NCEI"
page-layout: full
---

### How to get into the NOAA David Skaggs Research Center {#getting-into-noaa-office}

#### At 325 Broadway, Boulder, CO

### Directions {#directions}

Directions for getting to the David Skaggs Research Center can be found at this [link](https://esrl.noaa.gov/about/pdf/DIA-DSRC-map-071014.pdf).

For more information visit - [How to get into the NOAA office on first day](https://esrl.noaa.gov/about/visiting.html)

### Dress Code

Team Fish at NCEI has a relaxed environment when it comes to the dress code. We describe ourselves as a step below business casual. No need to wear a blazer or a pencil skirt unless you experience the rare occasion when congressional staff or NOAA directors visit.

Typically jeans, shorts, t-shirts, and sneakers are totally acceptable, but do keep in mind that our team will make fun of you if you come in wearing something inappropriate. Nevertheless, many colleagues still dress in business casual attire so feel free to dress as you prefer!

A good rule of thumb is "wear what you want but avoid anything that you would not wear in front of your grandma."

Another reminder is that despite the summer heat, the office is relatively chilly no matter the time of the year, so we always recommend bringing a small jacket or sweater just in case.

### What to Bring

Items to bring are a water bottle to deal with the really dry climate, laptop and charger unless you know there will be a computer waiting for you, notebook and pen, and lunch. Emotional support stuffed animals are also welcome.
